ALTER TABLE "Run" ADD COLUMN "baseTeamScore" REAL NOT NULL DEFAULT 0;
ALTER TABLE "Run" ADD COLUMN "chemistryScore" REAL NOT NULL DEFAULT 0;
ALTER TABLE "Run" ADD COLUMN "chemistryMultiplier" REAL NOT NULL DEFAULT 1;
